name: release

on:
  push:
    branches:
      - 'main'

env:
  PYTHON_STANDALONE_VERSIONS: |
    - "20231002"
  PYTHON_VERSIONS: |
    - "3.10.13"
    - "3.11.6"
    - "3.12.0"

jobs:
  build-tag:
    strategy:
      matrix:
        pythonStandaloneVersion: ${{ fromJSON(env.PYTHON_STANDALONE_VERSIONS) }}
        pythonVersion: ${{ fromJSON(env.PYTHON_VERSIONS) }}
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-build-tag-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-tag-
      - name: build-tag
        run: |
          git config --global user.email "no@mail.exists"
          git config --global user.name "go-embed-python releaser"
          BUILD_NUM=$(./hack/next-build-num.sh ${{ matrix.pythonStandaloneVersion }} ${{ matrix.pythonVersion }})
          ./hack/build-tag.sh ${{ matrix.pythonStandaloneVersion }} ${{ matrix.pythonVersion }} $BUILD_NUM
          echo $BUILD_NUM > build-num
      - uses: actions/upload-artifact@v3
        with:
          name: workdir-${{ matrix.pythonStandaloneVersion }} ${{ matrix.pythonVersion }}
          path: ./

  tests:
    needs:
      - build-tag
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
          - windows-2019
        pythonStandaloneVersion: ${{ fromJSON(env.PYTHON_STANDALONE_VERSIONS) }}
        pythonVersion: ${{ fromJSON(env.PYTHON_VERSIONS) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-tests-
      - uses: actions/download-artifact@v3
        with:
          name: workdir-${{ matrix.pythonStandaloneVersion }} ${{ matrix.pythonVersion }}
      - name: checkout tag
        shell: bash
        run: |
          git checkout v0.0.0-${{ matrix.pythonVersion }}-${{ matrix.pythonStandaloneVersion }}-$(cat build-num)
      - name: run tests
        shell: bash
        run: |
          go test ./... -v

  release:
    needs:
      - tests
    strategy:
      matrix:
        pythonStandaloneVersion: ${{ fromJSON(env.PYTHON_STANDALONE_VERSIONS) }}
        pythonVersion: ${{ fromJSON(env.PYTHON_VERSIONS) }}
      fail-fast: false
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && github.ref_name == "main" }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workdir-${{ matrix.pythonStandaloneVersion }} ${{ matrix.pythonVersion }}
      - name: update remote url
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: push tag
        run: |
          git push origin v0.0.0-${{ matrix.pythonVersion }}-${{ matrix.pythonStandaloneVersion }}-$(cat build-num)
